server:
  port: 8761

spring:
  application.name: discovery-service
  main.allowBeanDefinitionOverriding: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    #enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0