spring:
  application:
    name: basket-service
  main:
    allow-bean-definition-overriding: true
  springdoc:
    swagger-ui:
      path: "/swagger-ui.html"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
